app: cityio-frontend
services:
  - name: web
    public: true
    template: http
    image: docker.prayujt.com/cityio-frontend
    ingress: cityio.prayujt.com
    features:
      - spa
    network:
      ports:
        - 80
