syntax = "proto3";

package cityio.service.v1;

import "cityio/entity/v1/army.proto";
import "cityio/entity/v1/bag.proto";
import "cityio/entity/v1/common.proto";
import "cityio/entity/v1/ids.proto";

message TrainTroopsRequest {
  cityio.entity.v1.BuildingId barracks_id = 1;
  cityio.entity.v1.TroopType type = 2;
  int32 count = 3;
}
message TrainTroopsResponse {}

message GetArmyRequest {
  cityio.entity.v1.ArmyId army_id = 1;
}
message GetArmyResponse {
  cityio.entity.v1.Army army = 1;
}

message MoveArmyRequest {
  cityio.entity.v1.ArmyId army_id = 1;
  cityio.entity.v1.Coordinates destination = 2;
}
message MoveArmyResponse {}

message MergeArmiesRequest {
  cityio.entity.v1.ArmyId target_army_id = 1;
  cityio.entity.v1.ArmyId source_army_id = 2;
}
message MergeArmiesResponse {}

message ListArmiesRequest {}
message ListArmiesResponse {
  repeated cityio.entity.v1.ArmyId army_ids = 1;
  cityio.entity.v1.EntityBag entities = 2;
}

// ArmyService trains, moves and merges armies.
service ArmyService {
  rpc TrainTroops(TrainTroopsRequest) returns (TrainTroopsResponse);
  rpc GetArmy(GetArmyRequest) returns (GetArmyResponse);
  rpc MoveArmy(MoveArmyRequest) returns (MoveArmyResponse);
  rpc MergeArmies(MergeArmiesRequest) returns (MergeArmiesResponse);
  rpc ListArmies(ListArmiesRequest) returns (ListArmiesResponse);
}
