syntax = "proto3";

package cityio.service.v1;

import "cityio/entity/v1/bag.proto";
import "cityio/entity/v1/ids.proto";

enum TileVisibilityState {
  TILE_VISIBILITY_STATE_UNSPECIFIED = 0;
  TILE_VISIBILITY_STATE_UNEXPLORED = 1;
  TILE_VISIBILITY_STATE_EXPLORED = 2;
  TILE_VISIBILITY_STATE_VISIBLE = 3;
}

message TileVisibility {
  cityio.entity.v1.TileId tile_id = 1;
  TileVisibilityState state = 2;
}

message EntityIdBag {
  repeated cityio.entity.v1.UserId user_ids = 1;
  repeated cityio.entity.v1.CityId city_ids = 2;
  repeated cityio.entity.v1.BuildingId building_ids = 3;
  repeated cityio.entity.v1.ArmyId army_ids = 4;
  repeated cityio.entity.v1.TileId tile_ids = 5;
}

message StateSnapshot {
  cityio.entity.v1.EntityBag entities = 1;
  repeated TileVisibility tile_visibility = 2;
}

message StateDelta {
  cityio.entity.v1.EntityBag upserts = 1;
  EntityIdBag deleted = 2;
  EntityIdBag hidden = 3;
  repeated TileVisibility tile_visibility = 4;
}
