syntax = "proto3";

package cityio.entity.v1;

message UserId {
  string value = 1;
}

message CityId {
  string value = 1;
}

message BuildingId {
  string value = 1;
}

message ArmyId {
  string value = 1;
}

message ArmyMarchId {
  string value = 1;
}

message TrainingOrderId {
  string value = 1;
}

message TileId {
  int32 x = 1;
  int32 y = 2;
}

message EntityIdBag {
  repeated UserId user_ids = 1;
  repeated CityId city_ids = 2;
  repeated BuildingId building_ids = 3;
  repeated ArmyId army_ids = 4;
  repeated TileId tile_ids = 5;
  repeated ArmyMarchId army_march_ids = 6;
}
